-- Enable useful extensions
create extension if not exists "uuid-ossp";

drop table if exists public.discount_campaign_variants cascade;
drop table if exists public.discount_campaigns cascade;
drop table if exists public.product_categories cascade;
drop table if exists public.variant_sizes cascade;
drop table if exists public.product_variants cascade;
drop table if exists public.products cascade;
drop table if exists public.categories cascade;
drop table if exists public.brands cascade;
drop table if exists public.inventory cascade;
drop table if exists public.storefront_settings cascade;

create table if not exists public.brands (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  constraint brands_name_unique unique (name)
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  constraint categories_name_unique unique (name)
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  image_url text,
  brand_id bigint references public.brands(id) on delete set null,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.product_categories (
  product_id bigint not null references public.products(id) on delete cascade,
  category_id bigint not null references public.categories(id) on delete cascade,
  created_at timestamptz not null default timezone('utc'::text, now()),
  constraint product_categories_pk primary key (product_id, category_id)
);

create index if not exists product_categories_category_idx on public.product_categories (category_id);

create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  sku text,
  color text,
  image_url text,
  description text,
  is_preorder boolean not null default false,
  is_active boolean not null default true,
  preorder_down_payment_type text not null default 'none',
  preorder_down_payment_value numeric(10, 2),
  preorder_message text,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  constraint product_variants_preorder_down_payment_type_check
    check (preorder_down_payment_type in ('none', 'percent', 'amount')),
  constraint product_variants_preorder_down_payment_value_check
    check (preorder_down_payment_value is null or preorder_down_payment_value >= 0),
  constraint product_variants_preorder_down_payment_percent_check
    check (
      preorder_down_payment_type != 'percent'
      or preorder_down_payment_value is null
      or preorder_down_payment_value <= 100
    )
);

create unique index if not exists product_variants_unique_option_idx
  on public.product_variants (
    product_id,
    coalesce(color, '')
  );

create table if not exists public.variant_sizes (
  id bigint generated by default as identity primary key,
  variant_id bigint not null references public.product_variants(id) on delete cascade,
  size text,
  price numeric(10, 2) not null,
  stock_quantity integer not null default 0,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create unique index if not exists variant_sizes_unique_option_idx
  on public.variant_sizes (variant_id, coalesce(size, ''));

create table if not exists public.discount_campaigns (
  id uuid primary key default uuid_generate_v4(),
  name text not null,
  description text,
  banner_image_url text,
  start_date date not null,
  end_date date not null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  constraint discount_campaigns_date_check check (end_date >= start_date)
);

create index if not exists discount_campaigns_active_idx
  on public.discount_campaigns (is_active, start_date, end_date);

create table if not exists public.discount_campaign_variants (
  id bigint generated by default as identity primary key,
  campaign_id uuid not null references public.discount_campaigns(id) on delete cascade,
  variant_id bigint not null references public.product_variants(id) on delete cascade,
  discount_percent numeric(5, 2) not null,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  constraint discount_campaign_variants_percent_check check (discount_percent >= 0 and discount_percent <= 100),
  constraint discount_campaign_variants_unique unique (campaign_id, variant_id)
);

create index if not exists discount_campaign_variants_variant_idx
  on public.discount_campaign_variants (variant_id);

create table if not exists public.payment_methods (
  id uuid primary key default uuid_generate_v4(),
  provider text not null,
  account_name text,
  instructions text,
  qr_code_url text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  constraint payment_methods_provider_unique unique (provider)
);

create unique index if not exists payment_methods_provider_idx on public.payment_methods (provider);

create table if not exists public.storefront_settings (
  id integer primary key default 1,
  home_collection_mode text not null default 'brand',
  home_banner_manual_product_ids integer[] not null default '{}'::integer[],
  highlight_popular_hero boolean not null default true,
  highlight_latest_hero boolean not null default true,
  nav_collections_enabled boolean not null default true,
  favicon_url text,
  theme_config jsonb not null default '{}'::jsonb,
  shipping_default_fee numeric(10, 2) not null default 300,
  shipping_region_overrides jsonb not null default '{}'::jsonb,
  vat_enabled boolean not null default true,
  pickup_enabled boolean not null default true,
  pickup_location_name text,
  pickup_location_unit text,
  pickup_location_lot text,
  pickup_location_street text,
  pickup_location_city text,
  pickup_location_region text,
  pickup_location_zip_code text,
  pickup_location_country text default 'Philippines',
  pickup_location_notes text,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  constraint storefront_settings_singleton check (id = 1),
  constraint storefront_settings_home_collection_mode_check check (home_collection_mode in ('brand', 'category'))
);

create unique index if not exists storefront_settings_singleton_idx on public.storefront_settings (id);

-- Orders table
create table if not exists public.orders (
  id text primary key,
  payment_method text not null,
  proof_of_payment_url text,
  customer_first_name text not null,
  customer_last_name text not null,
  customer_phone text not null,
  customer_email text not null,
  instagram_handle text,
  delivery_unit text,
  delivery_lot text,
  delivery_street text not null,
  delivery_city text not null,
  delivery_region text not null,
  delivery_zip_code text not null,
  delivery_country text not null,
  fulfillment_method text not null default 'delivery',
  pickup_location_name text,
  pickup_location_unit text,
  pickup_location_lot text,
  pickup_location_street text,
  pickup_location_city text,
  pickup_location_region text,
  pickup_location_zip_code text,
  pickup_location_country text,
  pickup_location_notes text,
  pickup_scheduled_date date,
  pickup_scheduled_time text,
  order_items jsonb not null default '[]'::jsonb,
  subtotal numeric(10, 2) not null default 0,
  vat numeric(10, 2) not null default 0,
  shipping_fee numeric(10, 2) not null default 0,
  total numeric(10, 2) not null default 0,
  tracking_id text,
  status text not null default 'For Evaluation',
  is_read boolean not null default false,
  inventory_adjusted boolean not null default false,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  constraint orders_fulfillment_method_check check (fulfillment_method in ('delivery', 'pickup'))
);

-- Indices to speed up admin views
create index if not exists orders_status_idx on public.orders (status);
create index if not exists orders_created_at_idx on public.orders (created_at desc);

create table if not exists public.instagram_connections (
  id uuid primary key default uuid_generate_v4(),
  page_id text not null,
  page_name text,
  page_access_token text not null,
  instagram_business_account_id text not null,
  instagram_username text,
  user_access_token text not null,
  user_access_token_expires_at timestamptz,
  scopes text[] not null default array[]::text[],
  status text not null default 'connected',
  metadata jsonb not null default '{}'::jsonb,
  connected_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create unique index if not exists instagram_connections_page_id_idx on public.instagram_connections (page_id);
create unique index if not exists instagram_connections_ig_account_idx on public.instagram_connections (instagram_business_account_id);

create table if not exists public.instagram_oauth_sessions (
  id uuid primary key default uuid_generate_v4(),
  state text not null,
  long_lived_user_token text not null,
  long_lived_user_token_expires_at timestamptz,
  pages jsonb not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  expires_at timestamptz not null default timezone('utc'::text, now()) + interval '15 minutes',
  consumed_at timestamptz
);

create unique index if not exists instagram_oauth_sessions_state_idx on public.instagram_oauth_sessions (state);
create index if not exists instagram_oauth_sessions_expires_at_idx on public.instagram_oauth_sessions (expires_at);

create table if not exists public.chatbot_conversations (
  id uuid primary key default uuid_generate_v4(),
  connection_id uuid not null references public.instagram_connections(id) on delete cascade,
  instagram_user_id text not null,
  instagram_username text,
  stage text not null default 'initial',
  context jsonb not null default '{}'::jsonb,
  cart jsonb not null default '[]'::jsonb,
  last_user_message text,
  last_bot_message text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  constraint chatbot_conversations_unique_user_connection unique (connection_id, instagram_user_id)
);

-- Helper to keep updated_at fresh
create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_brands_updated_at on public.brands;
drop trigger if exists set_categories_updated_at on public.categories;
drop trigger if exists set_products_updated_at on public.products;
drop trigger if exists set_product_variants_updated_at on public.product_variants;
drop trigger if exists set_storefront_settings_updated_at on public.storefront_settings;
drop trigger if exists set_discount_campaigns_updated_at on public.discount_campaigns;
drop trigger if exists set_discount_campaign_variants_updated_at on public.discount_campaign_variants;

create trigger set_brands_updated_at
before update on public.brands
for each row
execute function public.set_updated_at();

create trigger set_categories_updated_at
before update on public.categories
for each row
execute function public.set_updated_at();

create trigger set_products_updated_at
before update on public.products
for each row
execute function public.set_updated_at();

create trigger set_product_variants_updated_at
before update on public.product_variants
for each row
execute function public.set_updated_at();

create trigger set_storefront_settings_updated_at
before update on public.storefront_settings
for each row
execute function public.set_updated_at();

create trigger set_discount_campaigns_updated_at
before update on public.discount_campaigns
for each row
execute function public.set_updated_at();

create trigger set_discount_campaign_variants_updated_at
before update on public.discount_campaign_variants
for each row
execute function public.set_updated_at();

drop trigger if exists set_variant_sizes_updated_at on public.variant_sizes;
create trigger set_variant_sizes_updated_at
before update on public.variant_sizes
for each row
execute function public.set_updated_at();

drop trigger if exists set_payment_methods_updated_at on public.payment_methods;
create trigger set_payment_methods_updated_at
before update on public.payment_methods
for each row
execute function public.set_updated_at();

drop trigger if exists set_orders_updated_at on public.orders;
create trigger set_orders_updated_at
before update on public.orders
for each row
execute function public.set_updated_at();

drop trigger if exists set_instagram_connections_updated_at on public.instagram_connections;
create trigger set_instagram_connections_updated_at
before update on public.instagram_connections
for each row
execute function public.set_updated_at();

drop trigger if exists set_instagram_oauth_sessions_updated_at on public.instagram_oauth_sessions;
create trigger set_instagram_oauth_sessions_updated_at
before update on public.instagram_oauth_sessions
for each row
execute function public.set_updated_at();

drop trigger if exists set_chatbot_conversations_updated_at on public.chatbot_conversations;
create trigger set_chatbot_conversations_updated_at
before update on public.chatbot_conversations
for each row
execute function public.set_updated_at();

-- Basic Row Level Security posture (service role bypasses these)
alter table public.brands enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_variants enable row level security;
alter table public.product_categories enable row level security;
alter table public.orders enable row level security;
alter table public.payment_methods enable row level security;
alter table public.discount_campaigns enable row level security;
alter table public.discount_campaign_variants enable row level security;
alter table public.instagram_connections enable row level security;
alter table public.instagram_oauth_sessions enable row level security;
alter table public.chatbot_conversations enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where tablename = 'brands' and policyname = 'Allow public read brands'
  ) then
    create policy "Allow public read brands"
      on public.brands
      for select
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies where tablename = 'categories' and policyname = 'Allow public read categories'
  ) then
    create policy "Allow public read categories"
      on public.categories
      for select
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies where tablename = 'products' and policyname = 'Allow public read products'
  ) then
    create policy "Allow public read products"
      on public.products
      for select
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies where tablename = 'product_variants' and policyname = 'Allow public read variants'
  ) then
    create policy "Allow public read variants"
      on public.product_variants
      for select
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies where tablename = 'product_categories' and policyname = 'Allow service role full access product categories'
  ) then
    create policy "Allow service role full access product categories"
      on public.product_categories
      using (auth.role() = 'service_role')
      with check (auth.role() = 'service_role');
  end if;

  if not exists (
    select 1 from pg_policies where tablename = 'orders' and policyname = 'Allow service role full access orders'
  ) then
    create policy "Allow service role full access orders"
      on public.orders
      using (auth.role() = 'service_role')
      with check (auth.role() = 'service_role');
  end if;

  if not exists (
    select 1 from pg_policies where tablename = 'payment_methods' and policyname = 'Allow service role full access payment methods'
  ) then
    create policy "Allow service role full access payment methods"
      on public.payment_methods
      using (auth.role() = 'service_role')
      with check (auth.role() = 'service_role');
  end if;

  if not exists (
    select 1 from pg_policies where tablename = 'discount_campaigns' and policyname = 'Allow service role full access discount campaigns'
  ) then
    create policy "Allow service role full access discount campaigns"
      on public.discount_campaigns
      using (auth.role() = 'service_role')
      with check (auth.role() = 'service_role');
  end if;

  if not exists (
    select 1 from pg_policies where tablename = 'discount_campaign_variants' and policyname = 'Allow service role full access discount campaign variants'
  ) then
    create policy "Allow service role full access discount campaign variants"
      on public.discount_campaign_variants
      using (auth.role() = 'service_role')
      with check (auth.role() = 'service_role');
  end if;

  if not exists (
    select 1 from pg_policies where tablename = 'instagram_connections' and policyname = 'Allow service role full access instagram connections'
  ) then
    create policy "Allow service role full access instagram connections"
      on public.instagram_connections
      using (auth.role() = 'service_role')
      with check (auth.role() = 'service_role');
  end if;

  if not exists (
    select 1 from pg_policies where tablename = 'instagram_oauth_sessions' and policyname = 'Allow service role full access instagram oauth sessions'
  ) then
    create policy "Allow service role full access instagram oauth sessions"
      on public.instagram_oauth_sessions
      using (auth.role() = 'service_role')
      with check (auth.role() = 'service_role');
  end if;

  if not exists (
    select 1 from pg_policies where tablename = 'chatbot_conversations' and policyname = 'Allow service role full access chatbot conversations'
  ) then
    create policy "Allow service role full access chatbot conversations"
      on public.chatbot_conversations
      using (auth.role() = 'service_role')
      with check (auth.role() = 'service_role');
  end if;
end;
$$;
