name = "chirp-copilot"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "chirp-db"
database_id = "e7d8226b-a4e0-4b52-96b8-279008714213"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "chirp-uploads"
